-- V3: Create tickets table
CREATE TABLE tickets (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id     BIGINT       NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
    title       VARCHAR(255) NOT NULL,
    description TEXT,
    priority    VARCHAR(10)  NOT NULL,
    status      VARCHAR(20)  NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP
);

CREATE INDEX idx_tickets_room    ON tickets(room_id);
CREATE INDEX idx_tickets_status  ON tickets(status);
CREATE INDEX idx_tickets_priority ON tickets(priority);
